package wbs.generics;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;


public class PersonenUtilBB {
	@SuppressWarnings("unchecked")
	public static List<Person> getPersonen(String filename) {
		InputStream fis = null;
		List<Person> list = null;
		try {
			fis = new FileInputStream(filename);
			ObjectInputStream o = new ObjectInputStream(fis);
			list = (List<Person>) o.readObject() ;
			o.close();
		} catch (IOException e) {
			System.err.println(e);
		} catch (ClassNotFoundException e) {
			System.err.println(e);
		} finally {
			try {
				fis.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return list;
	};

	public static void main(String[] args) {
		List<Person> personen = new ArrayList<>();

		personen.add(new Person("Michael", 1963, "männlich"));
		personen.add(new Person("Ute", 1943, "weiblich"));
		personen.add(new Person("Samuil", 1957, "männlich"));
		personen.add(new Person("Madeleine", 1978, "weiblich"));
		personen.add(new Person("Grzegorz", 1979, "männlich"));
		personen.add(new Person("Markus", 1975, "männlich"));
		personen.add(new Person("Bärbel", 1960, "weiblich"));
		personen.add(new Person("Alexander", 1972, "männlich"));
		personen.add(new Person("Klaus", 1956, "männlich"));
		personen.add(new Person("Irena", 1946, "weiblich"));
		personen.add(new Person("Nicole", 1969, "weiblich"));
		personen.add(new Person("Reinhard", 1936, "männlich"));
		personen.add(new Person("Norbert", 1957, "männlich"));
		personen.add(new Person("Ersin", 1980, "männlich"));
		personen.add(new Person("Wolfgang", 1956, "männlich"));
		personen.add(new Person("Darlen", 1953, "weiblich"));
		personen.add(new Person("Korkmaz", 1975, "männlich"));
		personen.add(new Person("Karl-Dieter", 1953, "männlich"));
		personen.add(new Person("Gerhard", 1932, "männlich"));
		personen.add(new Person("Doritha", 1946, "weiblich"));
		personen.add(new Person("Jutta", 1965, "weiblich"));
		personen.add(new Person("Ursula", 1934, "weiblich"));
		personen.add(new Person("Renate", 1959, "weiblich"));
		personen.add(new Person("Barbara", 1963, "weiblich"));
		personen.add(new Person("Klara", 1985, "weiblich"));
		personen.add(new Person("Herbert", 1938, "männlich"));
		personen.add(new Person("Jörg", 1962, "männlich"));
		personen.add(new Person("Heidrun", 1950, "weiblich"));
		personen.add(new Person("Andreas", 1964, "männlich"));
		personen.add(new Person("Susanne", 1958, "weiblich"));
		personen.add(new Person("Klaus", 1954, "männlich"));
		personen.add(new Person("Rainer", 1970, "männlich"));
		personen.add(new Person("Ursula", 1952, "weiblich"));
		personen.add(new Person("Klaus", 1960, "männlich"));
		personen.add(new Person("Corena", 1955, "weiblich"));
		personen.add(new Person("Bruno", 1944, "männlich"));
		personen.add(new Person("Bernd", 1953, "männlich"));
		personen.add(new Person("Renata", 1970, "weiblich"));
		personen.add(new Person("Manfred", 1951, "männlich"));
		personen.add(new Person("Hans-Dieter", 1945, "männlich"));
		personen.add(new Person("Erika", 1957, "weiblich"));
		personen.add(new Person("Iris", 1965, "weiblich"));
		personen.add(new Person("Britta", 1977, "weiblich"));
		personen.add(new Person("Wilfried", 1945, "männlich"));
		personen.add(new Person("Dieter", 1952, "männlich"));
		personen.add(new Person("Ulrich", 1957, "männlich"));
		personen.add(new Person("Jutta", 1947, "weiblich"));
		personen.add(new Person("Karwan", 1968, "männlich"));
		personen.add(new Person("Dora", 1931, "weiblich"));
		personen.add(new Person("Christina", 1956, "weiblich"));
		personen.add(new Person("Lothar", 1936, "männlich"));
		personen.add(new Person("Hans-Gerd", 1966, "männlich"));
		personen.add(new Person("Regina", 1954, "weiblich"));
		personen.add(new Person("Michael", 1962, "männlich"));
		personen.add(new Person("Ellen", 1930, "weiblich"));
		personen.add(new Person("Pietro", 1975, "männlich"));
		personen.add(new Person("Barbara", 1945, "weiblich"));
		personen.add(new Person("Hildegard", 1941, "weiblich"));
		personen.add(new Person("Martina", 1972, "weiblich"));
		personen.add(new Person("Stefan", 1968, "männlich"));
		personen.add(new Person("Silke", 1961, "weiblich"));
		personen.add(new Person("Petra c/o Herrn Ungefrohren", 1959, "weiblich"));
		personen.add(new Person("Christoph", 1959, "männlich"));
		personen.add(new Person("Wilfried", 1954, "männlich"));
		personen.add(new Person("Elke", 1966, "weiblich"));
		personen.add(new Person("Andreas", 1976, "männlich"));
		personen.add(new Person("Magdalena", 1977, "weiblich"));
		personen.add(new Person("Klaus-Peter", 1952, "männlich"));
		personen.add(new Person("Dr. Ute", 1967, "weiblich"));
		personen.add(new Person("Volker", 1970, "männlich"));
		personen.add(new Person("Viola", 1964, "weiblich"));
		personen.add(new Person("Horst", 1945, "männlich"));
		personen.add(new Person("Michael", 1955, "männlich"));
		personen.add(new Person("Ngoc Anh", 1981, "männlich"));
		personen.add(new Person("Peter", 1956, "männlich"));
		personen.add(new Person("Hans-Joachim", 1957, "männlich"));
		personen.add(new Person("Karin", 1957, "weiblich"));
		personen.add(new Person("Ute", 1955, "weiblich"));
		personen.add(new Person("Björn", 1971, "männlich"));
		personen.add(new Person("Katharina", 1967, "weiblich"));
		personen.add(new Person("Oliver", 1974, "männlich"));
		personen.add(new Person("Markus", 1965, "männlich"));
		personen.add(new Person("Sabine", 1968, "weiblich"));
		personen.add(new Person("Klaus-Dieter", 1941, "männlich"));
		personen.add(new Person("Petra", 1958, "weiblich"));
		personen.add(new Person("Gerda", 1959, "weiblich"));
		personen.add(new Person("Klaus", 1958, "männlich"));
		personen.add(new Person("Ingrid", 1952, "weiblich"));
		personen.add(new Person("Parviz", 1954, "männlich"));
		personen.add(new Person("Pierre", 1967, "männlich"));
		personen.add(new Person("Cengiz", 1964, "männlich"));
		personen.add(new Person("Heiko", 1974, "männlich"));
		personen.add(new Person("Bärbel", 1948, "weiblich"));
		personen.add(new Person("Uta", 1946, "weiblich"));
		personen.add(new Person("Michael-Patrick", 1969, "männlich"));
		personen.add(new Person("Hans-Karl", 1943, "männlich"));
		personen.add(new Person("Reiner", 1959, "männlich"));
		personen.add(new Person("Jutta", 1939, "weiblich"));
		personen.add(new Person("Gudrun", 1949, "weiblich"));
		personen.add(new Person("Dorothea", 1939, "weiblich"));
		personen.add(new Person("Jan", 1985, "männlich"));
		personen.add(new Person("Anna", 1974, "weiblich"));
		personen.add(new Person("Irmgard", 1934, "weiblich"));
		personen.add(new Person("Dirk", 1963, "männlich"));
		personen.add(new Person("Fernando", 1954, "männlich"));
		personen.add(new Person("Martin", 1960, "männlich"));
		personen.add(new Person("Roland", 1964, "männlich"));
		personen.add(new Person("Angelika", 1953, "weiblich"));
		personen.add(new Person("Karl-Heinz", 1956, "männlich"));
		personen.add(new Person("Edeltraud", 1957, "weiblich"));
		personen.add(new Person("Bettina", 1961, "weiblich"));
		personen.add(new Person("Michael", 1943, "männlich"));
		personen.add(new Person("Otto", 1951, "männlich"));
		personen.add(new Person("Corrina", 1966, "weiblich"));
		personen.add(new Person("Danuta", 1959, "weiblich"));
		personen.add(new Person("Gitta", 1944, "weiblich"));
		personen.add(new Person("Ulrike", 1965, "weiblich"));
		personen.add(new Person("Björn", 1971, "männlich"));
		personen.add(new Person("Barbara", 1962, "weiblich"));
		personen.add(new Person("Gitta", 1954, "weiblich"));
		personen.add(new Person("Bettina", 1965, "weiblich"));
		personen.add(new Person("Marion", 1955, "weiblich"));
		personen.add(new Person("Ina", 1975, "weiblich"));
		personen.add(new Person("Anja", 1974, "weiblich"));
		personen.add(new Person("Ekkehard", 1967, "männlich"));
		personen.add(new Person("Thomas-Wolfgang", 1968, "männlich"));
		personen.add(new Person("Günther", 1942, "männlich"));
		personen.add(new Person("Volker", 1971, "männlich"));
		personen.add(new Person("Kristina", 1971, "weiblich"));
		personen.add(new Person("Florian", 1954, "männlich"));
		personen.add(new Person("Lars", 1968, "männlich"));
		personen.add(new Person("André", 1975, "männlich"));
		personen.add(new Person("Klaudia", 1953, "weiblich"));
		personen.add(new Person("Bernhard", 1953, "männlich"));
		personen.add(new Person("Klaus", 1940, "männlich"));
		personen.add(new Person("Sonja", 1973, "weiblich"));
		personen.add(new Person("Karsten - M.", 1941, "männlich"));
		personen.add(new Person("Dirk", 1958, "männlich"));
		personen.add(new Person("Dieter", 1952, "männlich"));
		personen.add(new Person("Anja", 1969, "weiblich"));
		personen.add(new Person("Britta", 1969, "weiblich"));
		personen.add(new Person("Wolfgang", 1953, "männlich"));
		personen.add(new Person("Carmen", 1950, "weiblich"));
		personen.add(new Person("Christina", 1966, "weiblich"));
		personen.add(new Person("Joachim", 1940, "männlich"));
		personen.add(new Person("Peter", 1945, "männlich"));
		personen.add(new Person("Waltraut", 1935, "weiblich"));
		personen.add(new Person("Karl-Heinz", 1940, "männlich"));
		personen.add(new Person("Ingeborg", 1954, "weiblich"));
		personen.add(new Person("Dennis", 1977, "männlich"));
		personen.add(new Person("Jiuxin", 1970, "männlich"));
		personen.add(new Person("Manfred", 1947, "männlich"));
		personen.add(new Person("Ahmad", 1982, "männlich"));
		personen.add(new Person("Amja", 1970, "weiblich"));
		personen.add(new Person("Michael", 1960, "männlich"));
		personen.add(new Person("Iris", 1960, "weiblich"));
		personen.add(new Person("Reinhard", 1947, "männlich"));
		personen.add(new Person("Ulrich", 1944, "männlich"));
		personen.add(new Person("Norbert", 1953, "männlich"));
		personen.add(new Person("Werner", 1954, "männlich"));
		personen.add(new Person("Thomas", 1983, "männlich"));
		personen.add(new Person("Ali", 1980, "männlich"));
		personen.add(new Person("Sabine", 1963, "weiblich"));
		personen.add(new Person("Olaf", 1973, "männlich"));
		personen.add(new Person("Udo", 1964, "männlich"));
		personen.add(new Person("Bernd", 1966, "männlich"));
		personen.add(new Person("Andreas", 1966, "männlich"));
		personen.add(new Person("Yulia", 1983, "weiblich"));
		personen.add(new Person("H.-Albert", 1934, "männlich"));
		personen.add(new Person("Walter", 1928, "männlich"));
		personen.add(new Person("Stefan", 1976, "männlich"));
		personen.add(new Person("Michael", 1962, "männlich"));
		personen.add(new Person("Torsten", 1970, "männlich"));
		personen.add(new Person("Friederike", 1942, "weiblich"));
		personen.add(new Person("Gabriele", 1950, "weiblich"));
		personen.add(new Person("Eva", 1950, "weiblich"));
		personen.add(new Person("Klaus-Dieter", 1942, "männlich"));
		personen.add(new Person("Martina", 1963, "weiblich"));
		personen.add(new Person("Hans-Günter", 1952, "männlich"));
		personen.add(new Person("Angelika", 1954, "weiblich"));
		personen.add(new Person("Heinrich", 1934, "männlich"));
		personen.add(new Person("Robert", 1953, "männlich"));
		personen.add(new Person("Carsten", 1969, "männlich"));
		personen.add(new Person("Doris", 1969, "weiblich"));
		personen.add(new Person("Alexandra", 1973, "weiblich"));
		personen.add(new Person("Elfriede", 1940, "weiblich"));
		personen.add(new Person("Lieselotte", 1933, "weiblich"));
		personen.add(new Person("Dr. Jens", 1979, "männlich"));
		personen.add(new Person("Alina", 1959, "weiblich"));
		personen.add(new Person("Bruno", 1960, "männlich"));
		personen.add(new Person("Aneta", 1978, "weiblich"));
		personen.add(new Person("Rolf", 1943, "männlich"));
		personen.add(new Person("Bärbel", 1966, "weiblich"));
		personen.add(new Person("Rita", 1943, "weiblich"));
		personen.add(new Person("Nils", 1973, "männlich"));
		personen.add(new Person("Klaus", 1949, "männlich"));
		personen.add(new Person("Bettina", 1964, "weiblich"));
		personen.add(new Person("Ursula", 1950, "weiblich"));
		personen.add(new Person("Johanna", 1937, "weiblich"));
		personen.add(new Person("Britta", 1982, "weiblich"));
		personen.add(new Person("Cordula", 1968, "weiblich"));
		personen.add(new Person("Heike", 1973, "weiblich"));
		personen.add(new Person("Julia", 1981, "weiblich"));
		personen.add(new Person("Dirk", 1961, "männlich"));
		personen.add(new Person("Wilhelm", 1956, "männlich"));
		personen.add(new Person("Ingrid", 1946, "weiblich"));
		personen.add(new Person("Peter-Gerd", 1945, "männlich"));
		personen.add(new Person("Sandra", 1973, "weiblich"));
		personen.add(new Person("Sabina", 1966, "weiblich"));
		personen.add(new Person("Hiltrud", 1968, "weiblich"));
		personen.add(new Person("Marcel", 1962, "männlich"));
		personen.add(new Person("Christian", 1965, "männlich"));
		personen.add(new Person("Werner", 1947, "männlich"));
		personen.add(new Person("Tobias", 1971, "männlich"));
		personen.add(new Person("Klaus", 1965, "männlich"));
		personen.add(new Person("Vera", 1985, "weiblich"));
		personen.add(new Person("Heinz", 1939, "männlich"));
		personen.add(new Person("Anny", 1937, "weiblich"));
		personen.add(new Person("Kerstin", 1961, "weiblich"));
		personen.add(new Person("Maria", 1935, "weiblich"));
		personen.add(new Person("Irmhild", 1969, "weiblich"));
		personen.add(new Person("Manfred", 1946, "männlich"));
		personen.add(new Person("Heinrich", 1955, "männlich"));
		personen.add(new Person("Claus", 1935, "männlich"));
		personen.add(new Person("Werner", 1944, "männlich"));
		personen.add(new Person("Birgit", 1961, "weiblich"));
		personen.add(new Person("Wilhelma", 1945, "weiblich"));
		personen.add(new Person("Herbert", 1934, "männlich"));
		personen.add(new Person("Stefanie", 1978, "weiblich"));
		personen.add(new Person("Walter", 1935, "männlich"));
		personen.add(new Person("Inge", 1927, "weiblich"));
		personen.add(new Person("Ralf-Reimund", 1952, "männlich"));
		personen.add(new Person("Petra", 1965, "weiblich"));
		personen.add(new Person("Horst", 1940, "männlich"));
		personen.add(new Person("Dieter", 1944, "männlich"));
		personen.add(new Person("Maria", 1977, "weiblich"));
		personen.add(new Person("Frank", 1963, "männlich"));
		personen.add(new Person("Karola", 1942, "weiblich"));
		personen.add(new Person("Christiane", 1967, "weiblich"));
		personen.add(new Person("Roland", 1971, "männlich"));
		personen.add(new Person("Burgit", 1948, "weiblich"));
		personen.add(new Person("Anne-France", 1972, "weiblich"));
		personen.add(new Person("Vitali", 1973, "männlich"));
		personen.add(new Person("Susanne", 1937, "weiblich"));
		personen.add(new Person("Renate", 1952, "weiblich"));
		personen.add(new Person("Julia", 1974, "weiblich"));
		personen.add(new Person("Ingeborg", 1948, "weiblich"));
		personen.add(new Person("Monika", 1957, "weiblich"));
		personen.add(new Person("Milica", 1959, "weiblich"));
		personen.add(new Person("Annegret", 1966, "weiblich"));
		personen.add(new Person("Cornelia", 1961, "weiblich"));
		personen.add(new Person("Hans-Michael", 1953, "männlich"));
		personen.add(new Person("Manuela", 1967, "weiblich"));
		personen.add(new Person("Melanie", 1981, "weiblich"));
		personen.add(new Person("Katrin", 1978, "weiblich"));
		personen.add(new Person("Dominik", 1981, "männlich"));
		personen.add(new Person("Nikolaos", 1975, "männlich"));
		personen.add(new Person("Sofia", 1968, "weiblich"));
		personen.add(new Person("Anthimos", 1934, "männlich"));
		personen.add(new Person("Detlef", 1950, "männlich"));
		personen.add(new Person("Maj-Britt", 1968, "weiblich"));
		personen.add(new Person("Ingrid", 1944, "weiblich"));
		personen.add(new Person("Tanja", 1965, "weiblich"));
		personen.add(new Person("Dieter", 1941, "männlich"));
		personen.add(new Person("Markus", 1970, "männlich"));
		personen.add(new Person("Hannelore", 1935, "weiblich"));
		personen.add(new Person("Anke", 1962, "weiblich"));
		personen.add(new Person("Monica", 1958, "weiblich"));
		personen.add(new Person("Claudia", 1964, "weiblich"));
		personen.add(new Person("Erhard", 1952, "männlich"));
		personen.add(new Person("Olaf", 1948, "männlich"));
		personen.add(new Person("Renate", 1953, "weiblich"));
		personen.add(new Person("Inge", 1956, "weiblich"));
		personen.add(new Person("Heinz", 1935, "männlich"));
		personen.add(new Person("Rosemarie", 1942, "weiblich"));
		personen.add(new Person("Monika", 1939, "weiblich"));
		personen.add(new Person("Julia", 1979, "weiblich"));
		personen.add(new Person("Claudia", 1945, "weiblich"));
		personen.add(new Person("Heinz", 1951, "männlich"));
		personen.add(new Person("Kirsten", 1963, "weiblich"));
		personen.add(new Person("Thomas", 1969, "männlich"));
		personen.add(new Person("Stefan", 1969, "männlich"));
		personen.add(new Person("Solveig", 1971, "weiblich"));
		personen.add(new Person("Sven", 1960, "männlich"));
		personen.add(new Person("Jürgen", 1948, "männlich"));
		personen.add(new Person("Claudia", 1981, "weiblich"));
		personen.add(new Person("Günter", 1940, "männlich"));
		personen.add(new Person("Dieter", 1941, "männlich"));
		personen.add(new Person("Bodo", 1955, "männlich"));
		personen.add(new Person("Iris", 1956, "weiblich"));
		personen.add(new Person("Hans", 1951, "männlich"));
		personen.add(new Person("Salah", 1953, "männlich"));
		personen.add(new Person("Kirsten", 1962, "weiblich"));
		personen.add(new Person("Christina", 1968, "weiblich"));
		personen.add(new Person("Charlotte", 1955, "weiblich"));
		personen.add(new Person("Margot", 1937, "weiblich"));
		personen.add(new Person("Jan", 1984, "männlich"));
		personen.add(new Person("Eberhard", 1951, "männlich"));
		personen.add(new Person("Claudia", 1971, "weiblich"));
		personen.add(new Person("Brigitte", 1936, "weiblich"));
		personen.add(new Person("Eva", 1964, "weiblich"));
		personen.add(new Person("Günter", 1951, "männlich"));
		personen.add(new Person("Grischa", 1982, "männlich"));
		personen.add(new Person("Harry", 1956, "männlich"));
		personen.add(new Person("Erika", 1950, "weiblich"));
		personen.add(new Person("Arash", 1972, "männlich"));
		personen.add(new Person("Reinhard", 1930, "männlich"));
		personen.add(new Person("Rüdiger", 1961, "männlich"));
		personen.add(new Person("Jürgen", 1951, "männlich"));
		personen.add(new Person("Wolfgang", 1955, "männlich"));
		personen.add(new Person("Elena", 1965, "weiblich"));
		personen.add(new Person("Hans-Jürgen", 1951, "männlich"));
		personen.add(new Person("Tanja", 1982, "weiblich"));
		personen.add(new Person("Helmut", 1946, "männlich"));
		personen.add(new Person("Wilfried", 1937, "männlich"));
		personen.add(new Person("Martina", 1958, "weiblich"));
		personen.add(new Person("Wolfgang", 1982, "männlich"));
		personen.add(new Person("Ralph", 1976, "männlich"));
		personen.add(new Person("Peter", 1941, "männlich"));
		personen.add(new Person("Anke", 1941, "weiblich"));
		personen.add(new Person("Uta", 1958, "weiblich"));
		personen.add(new Person("Hans", 1936, "männlich"));
		personen.add(new Person("Ulrike", 1971, "weiblich"));
		personen.add(new Person("Nadine", 1982, "weiblich"));
		personen.add(new Person("Michaela", 1973, "weiblich"));
		personen.add(new Person("Waltraud", 1966, "weiblich"));
		personen.add(new Person("Tobias", 1964, "männlich"));
		personen.add(new Person("Eleonore", 1942, "weiblich"));
		personen.add(new Person("Rüdiger", 1954, "männlich"));
		personen.add(new Person("Werner", 1973, "männlich"));
		personen.add(new Person("Roland", 1947, "männlich"));
		personen.add(new Person("Julia", 1988, "weiblich"));
		personen.add(new Person("Bettina", 1945, "weiblich"));
		personen.add(new Person("Anna", 1980, "weiblich"));
		personen.add(new Person("Birgit", 1962, "weiblich"));
		personen.add(new Person("Gerhard", 1935, "männlich"));
		personen.add(new Person("Ekkehard", 1943, "männlich"));
		personen.add(new Person("Wolfgang", 1940, "männlich"));
		personen.add(new Person("Manfred", 1954, "männlich"));
		personen.add(new Person("Cordula", 1961, "weiblich"));
		personen.add(new Person("Viktoria", 1985, "weiblich"));
		personen.add(new Person("Beatrice", 1964, "weiblich"));
		personen.add(new Person("Beatrix", 1957, "weiblich"));
		personen.add(new Person("Sigrid", 1951, "weiblich"));
		personen.add(new Person("Irmgard", 1938, "weiblich"));
		personen.add(new Person("Gerold", 1963, "männlich"));
		personen.add(new Person("Ute", 1940, "weiblich"));
		personen.add(new Person("Holger", 1962, "männlich"));
		personen.add(new Person("Alfredo", 1938, "männlich"));
		personen.add(new Person("Elke", 1940, "weiblich"));
		personen.add(new Person("Margret", 1941, "weiblich"));
		personen.add(new Person("Johann", 1956, "männlich"));
		personen.add(new Person("Eckhard", 1930, "männlich"));
		personen.add(new Person("Heike-Ingeborg", 1944, "weiblich"));
		personen.add(new Person("Edeltraut", 1954, "weiblich"));
		personen.add(new Person("Valentina", 1946, "weiblich"));
		personen.add(new Person("Christa", 1941, "weiblich"));
		personen.add(new Person("Thorsten", 1971, "männlich"));
		personen.add(new Person("Petra", 1954, "weiblich"));
		personen.add(new Person("Kirsten", 1968, "weiblich"));
		personen.add(new Person("Petra", 1968, "weiblich"));
		personen.add(new Person("Adrian", 1965, "männlich"));
		personen.add(new Person("Kirsten", 1965, "weiblich"));
		personen.add(new Person("Bernhard", 1957, "männlich"));
		personen.add(new Person("Edgara", 1933, "weiblich"));
		personen.add(new Person("Cornelia", 1952, "weiblich"));
		personen.add(new Person("Marlies", 1950, "weiblich"));
		personen.add(new Person("Daniela", 1981, "weiblich"));
		personen.add(new Person("Sabine", 1954, "weiblich"));
		personen.add(new Person("Andrea", 1966, "weiblich"));
		personen.add(new Person("Stefan", 1967, "männlich"));
		personen.add(new Person("Petra", 1966, "weiblich"));
		personen.add(new Person("Annette", 1966, "weiblich"));
		personen.add(new Person("Dimitri", 1977, "männlich"));
		personen.add(new Person("Wilhelm", 1942, "männlich"));
		personen.add(new Person("Andreas", 1963, "männlich"));
		personen.add(new Person("Andrea", 1966, "weiblich"));
		personen.add(new Person("Wolf-Jürgen", 1949, "männlich"));
		personen.add(new Person("Horst Jürgen", 1938, "männlich"));
		personen.add(new Person("Dr. Stefanie", 1974, "weiblich"));
		personen.add(new Person("Jürgen", 1949, "männlich"));
		personen.add(new Person("Carsten", 1971, "männlich"));
		personen.add(new Person("Brigitte", 1953, "weiblich"));
		personen.add(new Person("Falk", 1980, "männlich"));
		personen.add(new Person("Ilona", 1952, "weiblich"));
		personen.add(new Person("Udo", 1971, "männlich"));
		personen.add(new Person("Andrea", 1967, "weiblich"));
		personen.add(new Person("Gorden", 1965, "männlich"));
		personen.add(new Person("Ina", 1964, "weiblich"));
		personen.add(new Person("Eilert", 1971, "männlich"));
		personen.add(new Person("Helga", 1941, "weiblich"));
		personen.add(new Person("Hartmut", 1956, "männlich"));
		personen.add(new Person("Melanie", 1970, "weiblich"));
		personen.add(new Person("Jürgen", 1967, "männlich"));
		personen.add(new Person("Sigrid", 1938, "weiblich"));
		personen.add(new Person("Sergiy", 1975, "männlich"));
		personen.add(new Person("Gabriele", 1956, "weiblich"));
		personen.add(new Person("Frieda", 1923, "weiblich"));
		personen.add(new Person("Uwe", 1963, "männlich"));
		personen.add(new Person("Bernd", 1948, "männlich"));
		personen.add(new Person("Ewa", 1966, "weiblich"));
		personen.add(new Person("Waldemar", 1973, "männlich"));
		personen.add(new Person("Gerd", 1943, "männlich"));

		OutputStream fos = null;
		String filename = "E:\\bbehrensdorf\\personen.dat";
		try {
			fos = new FileOutputStream(filename);
			ObjectOutputStream o = new ObjectOutputStream(fos);
			o.writeObject(personen);
			o.close();
		} catch (IOException e) {
			System.err.println(e);
		} finally {
			try {
				fos.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

}
